apiVersion: v1
kind: Pod
metadata:
  name: jenkins-agent-pod
spec:
  containers:
  - name: jnlp
    image: ghcr.io/tsmp-falcon-platform/ci-bundle-utils
    imagePullPolicy: Always
    command: ["/usr/share/jenkins/jenkins-agent"]
    volumeMounts:
    - name: pseudo-jnlp
      mountPath: /usr/share/jenkins
    - name: bundleutils-cache
      mountPath: /opt/bundleutils/.cache
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 2000m
        memory: 2048Mi
  initContainers:
  - name: copy-agent-stuff
    image: cloudbees/cloudbees-core-agent:2.462.1.3
    command: ["sh", "-c", "cp /usr/share/jenkins/agent.jar /usr/local/bin/jenkins-agent /pseudo-jnlp/"]
    volumeMounts:
    - name: pseudo-jnlp
      mountPath: /pseudo-jnlp
  volumes:
  - name: pseudo-jnlp
    emptyDir: {}
  - name: bundleutils-cache
    persistentVolumeClaim:
        claimName: bundleutils-cache-pvc
